-- MySQL Script generated by MySQL Workbench
-- 08/03/16 14:16:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema soft-facture
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `soft-facture` ;

-- -----------------------------------------------------
-- Schema soft-facture
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soft-facture` DEFAULT CHARACTER SET utf8 ;
USE `soft-facture` ;

-- -----------------------------------------------------
-- Table `soft-facture`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft-facture`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NULL,
  `ci_usuario` VARCHAR(45) NULL,
  `telefono_usuariol` VARCHAR(45) NULL,
  `email_usuario` VARCHAR(45) NULL,
  `dia_aniadido` VARCHAR(45) NULL,
  `privilegios_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soft-facture`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft-facture`.`cliente` (
  `id_cliente` INT NOT NULL,
  `nombre_cliente` VARCHAR(45) NULL,
  `nit_cliente` INT NOT NULL,
  `telefono_cliente` CHAR(10) NULL,
  `email_cliente` VARCHAR(45) NULL,
  `direccion_cliente` VARCHAR(45) NULL,
  `estado_cliente` TINYINT(1) NULL,
  `dia_aniadido` DATE NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soft-facture`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft-facture`.`empresa` (
  `nit` INT NOT NULL,
  `nombre_empresa` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `pais` VARCHAR(20) NULL,
  `ciudad` VARCHAR(20) NULL,
  `telefono` INT NULL,
  `email` VARCHAR(45) NULL,
  `web` VARCHAR(45) NULL,
  PRIMARY KEY (`nit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soft-facture`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft-facture`.`factura` (
  `id_factura` INT NOT NULL,
  `numero_factura` INT NOT NULL,
  `fecha_factura` DATE NULL,
  `id_cliente` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `estado` TINYINT(1) NULL,
  `total_venta` VARCHAR(45) NULL,
  `empresa_nit` INT NOT NULL,
  PRIMARY KEY (`id_factura`, `id_cliente`, `id_usuario`, `empresa_nit`),
  INDEX `fk_factura_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_factura_cliente1_idx` (`id_cliente` ASC),
  INDEX `fk_factura_empresa1_idx` (`empresa_nit` ASC),
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `soft-facture`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `soft-facture`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_empresa1`
    FOREIGN KEY (`empresa_nit`)
    REFERENCES `soft-facture`.`empresa` (`nit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soft-facture`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft-facture`.`producto` (
  `id_producto` INT NOT NULL,
  `codigo_producto` VARCHAR(30) NULL,
  `nombre_producto` VARCHAR(45) NULL,
  `estado_producto` TINYINT(1) NULL,
  `precio_producto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soft-facture`.`detalle_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft-facture`.`detalle_factura` (
  `id_detalleFactura` INT NOT NULL,
  `id_factura` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NULL,
  `precio_venta` DOUBLE NULL,
  PRIMARY KEY (`id_factura`, `id_producto`, `id_detalleFactura`),
  INDEX `fk_factura_has_producto_producto1_idx` (`id_producto` ASC),
  INDEX `fk_factura_has_producto_factura1_idx` (`id_factura` ASC),
  CONSTRAINT `fk_factura_has_producto_factura1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `soft-facture`.`factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_has_producto_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `soft-facture`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soft-facture`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft-facture`.`almacen` (
  `id_producto` INT NOT NULL,
  `cantidad_producto` INT NULL,
  `cantidad_minima_producto` INT NULL,
  PRIMARY KEY (`id_producto`),
  CONSTRAINT `fk_almacen_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `soft-facture`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soft-facture`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft-facture`.`proveedor` (
  `id proveedor` INT NOT NULL,
  `nombre_proveedor` VARCHAR(45) NULL,
  `direccion_proveedor` VARCHAR(45) NULL,
  `telefono_proveedor` VARCHAR(45) NULL,
  `ciudad_proveedor` INT NULL,
  `pais_proveedor` VARCHAR(45) NULL,
  `email_proveedor` VARCHAR(45) NULL,
  `sitio_web_proveedor` VARCHAR(45) NULL,
  PRIMARY KEY (`id proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soft-facture`.`detalle_compra_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft-facture`.`detalle_compra_producto` (
  `id_detalle_producto` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id proveedor` INT NOT NULL,
  `dia_aniadido` DATETIME NULL,
  `detalle_compra_producto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_detalle_producto`, `id_producto`, `id proveedor`),
  INDEX `fk_detalle_compra_producto_producto1_idx` (`id_producto` ASC),
  INDEX `fk_detalle_compra_producto_proveedor1_idx` (`id proveedor` ASC),
  CONSTRAINT `fk_detalle_compra_producto_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `soft-facture`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_compra_producto_proveedor1`
    FOREIGN KEY (`id proveedor`)
    REFERENCES `soft-facture`.`proveedor` (`id proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
